services:
  web:
    build: .
    entrypoint: /mis/start.sh
    depends_on:
      - db
    volumes:
      - static:/mis/static/
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"

volumes:
  postgres_data:
  static:
