services:
  web:
    build: .
    entrypoint: /mis/start.sh
    depends_on:
      - db
    volumes:
      - static:/mis/static/
    ports:
      - "8080:8080"
    networks:
      - custom
  db:
    image: postgres:16.1
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"
    networks:
      - custom

volumes:
  postgres_data:
  static:

networks:
  custom:
    driver: bridge
