# Generated by Django 5.2.3 on 2025-06-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя клиники')),
                ('legal_address', models.CharField(max_length=1024, unique=True, verbose_name='Юридический адрес')),
                ('physical_address', models.CharField(max_length=1024, unique=True, verbose_name='Физический адрес')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
            },
        ),
    ]
